"""fix_ambiguous_foreign_keys

Revision ID: 5a73fa99cb58
Revises: 
Create Date: 2025-06-22 10:49:29.009494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '5a73fa99cb58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_AccessLog_EventType'))
        batch_op.drop_index(batch_op.f('IX_AccessLog_Timestamp'))
        batch_op.drop_index(batch_op.f('IX_AccessLog_User'))
        batch_op.drop_index(batch_op.f('idx_access_logs_timestamp'))
        batch_op.drop_constraint(batch_op.f('FK_AccessLog_Usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['user_id'], ['id'])

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('used',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))

    with op.batch_alter_table('solicitudes_baja', schema=None) as batch_op:
        batch_op.alter_column('motivo',
               existing_type=mssql.NTEXT(length=1073741823, collation='Modern_Spanish_CI_AS'),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('observaciones',
               existing_type=mssql.NTEXT(length=1073741823, collation='Modern_Spanish_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actualizado_por_id', sa.Integer(), nullable=True))
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               comment=None,
               existing_comment='Nombre de usuario generado automáticamente',
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128, collation='Modern_Spanish_CI_AS'),
               comment=None,
               existing_comment='Hash de contraseña con pepper',
               existing_nullable=False)
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('activo',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((1))'))
        batch_op.alter_column('nuevo_user',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((1))'))
        batch_op.alter_column('creado_en',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('actualizado_en',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
        batch_op.drop_index(batch_op.f('idx_usuarios_usuario'))
        batch_op.create_foreign_key(None, 'usuarios', ['actualizado_por_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Almacena información de usuarios del sistema'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Almacena información de usuarios del sistema',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_usuarios_usuario'), ['usuario'], unique=False)
        batch_op.alter_column('actualizado_en',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('creado_en',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
        batch_op.alter_column('nuevo_user',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((1))'))
        batch_op.alter_column('activo',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((1))'))
        batch_op.alter_column('fecha_nacimiento',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128, collation='Modern_Spanish_CI_AS'),
               comment='Hash de contraseña con pepper',
               existing_nullable=False)
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=50, collation='Modern_Spanish_CI_AS'),
               comment='Nombre de usuario generado automáticamente',
               existing_nullable=False)
        batch_op.drop_column('actualizado_por_id')

    with op.batch_alter_table('solicitudes_baja', schema=None) as batch_op:
        batch_op.alter_column('observaciones',
               existing_type=sa.Text(),
               type_=mssql.NTEXT(length=1073741823, collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('motivo',
               existing_type=sa.Text(),
               type_=mssql.NTEXT(length=1073741823, collation='Modern_Spanish_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('used',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_AccessLog_Usuario'), 'usuarios', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_access_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('IX_AccessLog_User'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('IX_AccessLog_Timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('IX_AccessLog_EventType'), ['event_type'], unique=False)

    # ### end Alembic commands ###
